### ISSUE TITLE
Fix Live Version

### ISSUE THREAD

**Issue by JohannesLipp** [schimatos/schimatos.org#13]
The live version, which should be available at http://schimatos.github.io/, redirects to http://rsmsrv01.nci.org.au:8080/schimatos/ and returns an error `ERR_EMPTY_RESPONSE`.

![image](https://user-images.githubusercontent.com/15930331/114669492-3e8f3480-9d02-11eb-8907-4d04fe619e3b.png)

Could you please fix this, thank you!

**Comment by srodriguez142857** [comment]
Hi.
Thank you for your interest in Schímatos.

Currently, in the hosting server, we are running a set of processes in order to collect data for another research project.
All other services on that server, including the hosting of Schimatos and its related graphs (triple store), are down and not available at the moment.

The processes will be run in a span of several days in the following weeks.
Hence, the Schímatos online demo will be available intermittently.
We apologize for this inconvenience.

If necessary, we can restore the service to be up for a specific time interval.
Please, let us know when would you like to use the online demo and for how long.
Thank you.

**Comment by jeswr** [comment]
As a general note - the codebase used by the live demo does not contain a significant amount development that we have done over the last ~6 months. For instance it does not include the redesigned internals for form generation that have been worked on [here](https://github.com/schimatos/shacl-form-react).

For reasons unrelated to the project I have been unable find the time to incorporate these changes into the demo versions of the tool as of yet.

**Comment by JohannesLipp** [comment]
Thank you for your replies!

@srodriguez142857 there is no urgent need for the live demo right now. A delayed availability after you finished ongoing operations is totally fine.

@jeswr Thanks for the hint. We will investigate the newer codebase you pointed me to. "Not enough time for interesting research" unfortunately is a common issue we usually need to handle... That repo however will probably suffice, so there is no need to keep the live version continuously up-to-date. Thanks!
